-- Create a new tab in the spawnmenu
hook.Add("PopulateToolMenu", "KeybindManager_PopulateToolMenu", function()
    spawnmenu.AddToolMenuOption("Utilities", "Keybind Manager", "KeybindManager", "Keybind Manager", "", "", function(panel)
        panel:ClearControls()

        local openMenuButton = vgui.Create("DButton", panel)
        openMenuButton:SetText("Open Keybind Manager")
        openMenuButton:Dock(TOP)
        openMenuButton:DockMargin(10, 10, 10, 0)
        openMenuButton:SetTextColor(Color(0,0,0))
        openMenuButton.DoClick = function()
            KeybindManager:OpenMenu()
        end

        local githubButton = vgui.Create("DButton", panel)
        githubButton:SetText("Go to GitHub Repository")
        githubButton:Dock(TOP)
        githubButton:DockMargin(10, 10, 10, 0)
        githubButton:SetTextColor(Color(0,0,0))
        githubButton.DoClick = function()
            gui.OpenURL("https://github.com/solaceware/KeybindManager")
        end

        local showChangelogsCheckbox = vgui.Create("DCheckBoxLabel", panel)
        showChangelogsCheckbox:SetText("Show Changelogs")
        showChangelogsCheckbox:SetConVar("show_changelogs")
        showChangelogsCheckbox:SetValue(GetConVar("show_changelogs"):GetBool())
        showChangelogsCheckbox:Dock(TOP)
        showChangelogsCheckbox:DockMargin(10, 10, 10, 0)
        showChangelogsCheckbox:SetTextColor(Color(0,0,0))

        local reportIssuesLabel = vgui.Create("DLabel", panel)
        reportIssuesLabel:SetText("Please report any issues on GitHub, not in the Steam Workshop comments. I don't check those on a regular basis.")
        reportIssuesLabel:SetWrap(true)
        reportIssuesLabel:SetAutoStretchVertical(true)
        reportIssuesLabel:Dock(TOP)
        reportIssuesLabel:DockMargin(10, 10, 10, 0)
        reportIssuesLabel:SetTextColor(Color(0,0,0))

        local creditLabel = vgui.Create("DLabel", panel)
        creditLabel:SetText("Keybind Manager by thatrtxdude")
        creditLabel:SetWrap(true)
        creditLabel:SetAutoStretchVertical(true)
        creditLabel:Dock(TOP)
        creditLabel:DockMargin(10, 10, 10, 0)
        creditLabel:SetTextColor(Color(0,0,0))
    end)
end)
